server:
  port: 8081
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID01
oauth2-server-url: http://localhost:8080
security:
  oauth2:
    client:
      client-id: client
      client-secret: client123
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
      access-token-uri: ${oauth2-server-url}/oauth/token
    resource:
      token-info-uri: ${oauth2-server-url}/oauth/check_token
#    resource:
#      jwt:
#        key-uri: ${oauth2-server-url}/oauth/token_key
#        key-value: xxx